# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import pylab as pl
import numpy as np


In [2]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
print df.head()

   admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0


## Part 1. Frequency Tables

#### 1. Let's create a frequency table of our variables

In [3]:
# frequency table for prestige and whether or not someone was admitted
prestige_freq_table = pd.crosstab(df.prestige, df.admit)
print 'counts'
print prestige_freq_table

prestige_freq_table_percents = pd.crosstab(df.prestige, df.admit).apply(lambda r: r/r.sum(), axis=1)
print 'percents'
print prestige_freq_table_percents

counts
admit      0   1
prestige        
1.0       28  33
2.0       95  53
3.0       93  28
4.0       55  12
percents
admit            0         1
prestige                    
1.0       0.459016  0.540984
2.0       0.641892  0.358108
3.0       0.768595  0.231405
4.0       0.820896  0.179104


## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

In [8]:
dummy_ranks = pd.get_dummies(df.prestige)
dummy_ranks.columns = ['prestige_1', 'prestige_2', 'prestige_3', 'prestige_4']
dummy_ranks

prestige_1  prestige_2  prestige_3  prestige_4
0             0           0           1           0
1             0           0           1           0
2             1           0           0           0
3             0           0           0           1
4             0           0           0           1
5             0           1           0           0
6             1           0           0           0
7             0           1           0           0
8             0           0           1           0
9             0           1           0           0
10            0           0           0           1
11            1           0           0           0
12            1           0           0           0
13            0           1           0           0
14            1           0           0           0
15            0           0           1           0
16            0           0           0           1
17            0           0           1           0
18            0           1           0           0
19            1           0           0           0
20            0           0           1           0
21            0           1           0           0
22            0           0           0           1
23            0           0           0           1
24            0           1           0           0
25            1           0           0           0
26            1           0           0           0
27            0           0           0           1
28            0           1           0           0
29            1           0           0           0
..          ...         ...         ...         ...
370           0           1           0           0
371           0           0           1           0
372           1           0           0           0
373           1           0           0           0
374           0           1           0           0
375           0           0           0           1
376           0           1           0           0
377           0           1           0           0
378           0           0           1           0
379           0           1           0           0
380           0           1           0           0
381           0           1           0           0
382           0           1           0           0
383           1           0           0           0
384           0           1           0           0
385           1           0           0           0
386           0           1           0           0
387           0           1           0           0
388           0           1           0           0
389           0           1           0           0
390           0           1           0           0
391           0           1           0           0
392           0           0           1           0
393           0           1           0           0
394           0           0           1           0
395           0           1           0           0
396           0           0           1           0
397           0           1           0           0
398           0           1           0           0
399           0           0           1           0

[397 rows x 4 columns]

#### 2.2 When modeling our class variables, how many do we need? 



Answer: 3

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In [9]:
cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_1':])
print handCalc.head()

   admit    gre   gpa  prestige_1  prestige_2  prestige_3  prestige_4
0      0  380.0  3.61           0           0           1           0
1      1  660.0  3.67           0           0           1           0
2      1  800.0  4.00           1           0           0           0
3      1  640.0  3.19           0           0           0           1
4      0  520.0  2.93           0           0           0           1


In [10]:
#crosstab prestige 1 admission 
# frequency table cutting prestige and whether or not someone was admitted

handCalc_freq_table = pd.crosstab(handCalc.prestige_1, handCalc.admit)
handCalc_freq_table

admit         0   1
prestige_1         
0           243  93
1            28  33

#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked college

In [11]:
odds_p1 = 33.0 / (33.0 + 28.0)
odds_p1

0.5409836065573771

#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

In [12]:
odds_not_p1 = 93. / (93. + 243.)
odds_not_p1

0.2767857142857143

#### 3.3 Calculate the odds ratio

In [13]:
odds_ratio = odds_p1 / odds_not_p1
odds_ratio

1.9545214172395557

#### 3.4 Write this finding in a sentenance: 

Answer: Your odds of admission to UCLA grad school are twice as favorable if you went to the most prestigious undergrad universities than if you didn't. 

#### 3.5 Print the cross tab for prestige_4

In [14]:
crosstab_p4 = pd.crosstab(handCalc.prestige_4, handCalc.admit)
crosstab_p4

admit         0    1
prestige_4          
0           216  114
1            55   12

#### 3.6 Calculate the OR 

In [15]:
odds_p4 = 12. / (12. + 55.)
odds_not_p4 = 114. / (114. + 216.)
odds_ratio_p4 = odds_p4 / odds_not_p4
odds_ratio_p4

0.5184603299293008

#### 3.7 Write this finding in a sentence

Answer: Your odds of admission to UCLA grad school and half as favorable if you went to the least prestigious undergrad universities than not. 

## Part 4. Analysis

In [16]:
# create a clean data frame for the regression
cols_to_keep = ['admit', 'gre', 'gpa']
data = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_2':])
print data.head()

   admit    gre   gpa  prestige_2  prestige_3  prestige_4
0      0  380.0  3.61           0           1           0
1      1  660.0  3.67           0           1           0
2      1  800.0  4.00           0           0           0
3      1  640.0  3.19           0           0           1
4      0  520.0  2.93           0           0           1


We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [17]:
# manually add the intercept
data['intercept'] = 1.0

#### 4.1 Set the covariates to a variable called train_cols

In [18]:
train_cols = data.loc[:, ['admit', 'gre', 'gpa', 'prestige_2', 'prestige_3', 'prestige_4']]

#### 4.2 Fit the model

In [19]:
data_stats = smf.ols(formula='admit ~ gre + gpa + prestige_2 + prestige_3 + prestige_4', data=data).fit()

#### 4.3 Print the summary results

In [20]:
data_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  admit   R-squared:                       0.099
Model:                            OLS   Adj. R-squared:                  0.087
Method:                 Least Squares   F-statistic:                     8.594
Date:                Mon, 22 May 2017   Prob (F-statistic):           9.71e-08
Time:                        21:59:26   Log-Likelihood:                -239.02
No. Observations:                 397   AIC:                             490.0
Df Residuals:                     391   BIC:                             513.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept     -0.2377      0.217     -1.095      0.274        -0.665     0.189
gre            0.0004      0.000      1.997      0.047      6.48e-06     0.001
gpa            0.1508      0.064      2.349      0.019         0.025     0.277
prestige_2    -0.1635      0.068     -2.407      0.017        -0.297    -0.030
prestige_3    -0.2910      0.070     -4.139      0.000        -0.429    -0.153
prestige_4    -0.3240      0.079     -4.082      0.000        -0.480    -0.168
==============================================================================
Omnibus:                      152.312   Durbin-Watson:                   1.946
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.314
Skew:                           0.678   Prob(JB):                     1.19e-11
Kurtosis:                       1.904   Cond. No.                     6.07e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.07e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### 4.4 Calculate the odds ratios of the coeffiencents and their 95% CI intervals

hint 1: np.exp(X)

hint 2: conf['OR'] = params
        
           conf.columns = ['2.5%', '97.5%', 'OR']

#### 4.5 Interpret the OR of Prestige_2

#### 4.6 Interpret the OR of GPA

Answer: gpa has slightly better odds of predicting admission

## Part 5: Predicted probablities


As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [35]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [36]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(data['gre'].min(), data['gre'].max(), 10)
print gres
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(data['gpa'].min(), data['gpa'].max(), 10)
print gpas
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))

[ 220.          284.44444444  348.88888889  413.33333333  477.77777778
  542.22222222  606.66666667  671.11111111  735.55555556  800.        ]
[ 2.26        2.45333333  2.64666667  2.84        3.03333333  3.22666667
  3.42        3.61333333  3.80666667  4.        ]


#### 5.1 Recreate the dummy variables

In [37]:
# do not understand the goal here
combos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
0    400 non-null float64
1    400 non-null float64
2    400 non-null float64
3    400 non-null float64
dtypes: float64(4)
memory usage: 12.6 KB


In [38]:
# recreate the dummy variables
# combos.head()
dummies = pd.get_dummies(combos)
dummies.head()
# keep only what we need for making predictions


0         1    2    3
0  220.0  2.260000  1.0  1.0
1  220.0  2.260000  2.0  1.0
2  220.0  2.260000  3.0  1.0
3  220.0  2.260000  4.0  1.0
4  220.0  2.453333  1.0  1.0

#### 5.2 Make predictions on the enumerated dataset

#### 5.3 Interpret findings for the last 4 observations

Answer: 

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.

In [48]:
import sklearn.linear_model as lm

model = lm.LogisticRegression()